<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>1 使用R语言获得数据 | 02-getting-started.utf8.md</title>
  <meta name="description" content="">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="1 使用R语言获得数据 | 02-getting-started.utf8.md" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1 使用R语言获得数据 | 02-getting-started.utf8.md" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  


<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-89938436-1', 'auto');
  ga('send', 'pageview');

</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path=""><a href="#getting-started"><i class="fa fa-check"></i><b>1</b> 使用R语言获得数据</a><ul>
<li class="chapter" data-level="1.1" data-path=""><a href="#r--rstudio"><i class="fa fa-check"></i><b>1.1</b> 什么是R 和 Rstudio?</a><ul>
<li class="chapter" data-level="1.1.1" data-path=""><a href="#-r--rstudio"><i class="fa fa-check"></i><b>1.1.1</b> 安装 R 和 RStudio</a></li>
<li class="chapter" data-level="1.1.2" data-path=""><a href="#rstudior"><i class="fa fa-check"></i><b>1.1.2</b> 在RStudio中使用R</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path=""><a href="#code"><i class="fa fa-check"></i><b>1.2</b> 如果开始编写R语言?</a><ul>
<li class="chapter" data-level="1.2.1" data-path=""><a href="#programming-concepts"><i class="fa fa-check"></i><b>1.2.1</b> 基本编程概念和术语</a></li>
<li class="chapter" data-level="1.2.2" data-path=""><a href="#section-1.2.2"><i class="fa fa-check"></i><b>1.2.2</b> 学习编程的提示</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path=""><a href="#packages"><i class="fa fa-check"></i><b>1.3</b> 什么是 R packages?</a><ul>
<li class="chapter" data-level="1.3.1" data-path=""><a href="#-package"><i class="fa fa-check"></i><b>1.3.1</b> 安装 Package</a></li>
<li class="chapter" data-level="1.3.2" data-path=""><a href="#-package"><i class="fa fa-check"></i><b>1.3.2</b> 加载 Package</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path=""><a href="#nycflights13"><i class="fa fa-check"></i><b>1.4</b> 探索 你的第一个数据集</a><ul>
<li class="chapter" data-level="1.4.1" data-path=""><a href="#nycflights13-package"><i class="fa fa-check"></i><b>1.4.1</b> nycflights13 package</a></li>
<li class="chapter" data-level="1.4.2" data-path=""><a href="#flights-"><i class="fa fa-check"></i><b>1.4.2</b> flights 数据集</a></li>
<li class="chapter" data-level="1.4.3" data-path=""><a href="#exploredataframes"><i class="fa fa-check"></i><b>1.4.3</b> 探索数据集</a></li>
<li class="chapter" data-level="1.4.4" data-path=""><a href="#section-1.4.4"><i class="fa fa-check"></i><b>1.4.4</b> 帮助文件</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path=""><a href="#section-1.5"><i class="fa fa-check"></i><b>1.5</b> 结论</a><ul>
<li class="chapter" data-level="1.5.1" data-path=""><a href="#section-1.5.1"><i class="fa fa-check"></i><b>1.5.1</b> 下一集有什么内容?</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<html>
<img src='https://moderndive.com/images/logos/wide_format.png' alt="ModernDive">
</html>
<!--bookdown:title:end-->
<!--bookdown:title:start-->
<div id="getting-started" class="section level1">
<h1><span class="header-section-number">1</span> 使用R语言获得数据</h1>
<p>开始使用R去探索数据前，先要了解以下几个重要内容：</p>
<ol style="list-style-type: decimal">
<li>什么是R 和 Rstudio ?</li>
<li>如果开始编写R语言 ?</li>
<li>什么是R package ?</li>
</ol>
<p>如果你己经了解这几个内容。你可以跳过以下部分</p>
<p><a href="#nycflights13">1.4</a> below introducing some of the datasets we will explore in depth in this book. Much of this chapter is based on two sources which you should feel free to use as references if you are looking for additional details:</p>
<ol style="list-style-type: decimal">
<li>ModernDive co-author Chester Ismay’s <a href="http://ismayc.github.io/rbasics-book">Getting used to R, RStudio, and R Markdown</a> <span class="citation">[@usedtor2016]</span>, which includes video screen recordings that you can follow along and pause as you learn.</li>
<li>DataCamp’s online tutorials. DataCamp is a browser-based interactive platform for learning data science and their tutorials will help facilitate your learning of the above concepts (and other topics in this book). Go to <a href="https://www.datacamp.com/">DataCamp</a> and create an account before continuing.</li>
</ol>
<hr />
<div id="r--rstudio" class="section level2">
<h2><span class="header-section-number">1.1</span> 什么是R 和 Rstudio?</h2>
<p>For much of this book, we will assume that you are using R via RStudio. First time users often confuse the two. At its simplest:</p>
<ul>
<li>R is like a car’s engine</li>
<li>RStudio is like a car’s dashboard</li>
</ul>
<table>
<thead>
<tr class="header">
<th align="center">R: Engine</th>
<th align="center">RStudio: Dashboard</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><img src="images/engine.jpg" alt="Drawing" style="height: 200px;"/></td>
<td align="center"><img src="images/dashboard.jpg" alt="Drawing" style="height: 200px;"/></td>
</tr>
</tbody>
</table>
<p>More precisely, R is a programming language that runs computations while RStudio is an <em>integrated development environment (IDE)</em> that provides an interface by adding many convenient features and tools. So the way of having access to a speedometer, rearview mirrors, and a navigation system makes driving much easier, using RStudio’s interface makes using R much easier as well.</p>
<p>Optional: For a more in-depth discussion on the difference between R and RStudio IDE, watch this <a href="https://campus.datacamp.com/courses/working-with-the-rstudio-ide-part-1/orientation?ex=1">DataCamp video (2m52s)</a>.</p>
<div id="-r--rstudio" class="section level3">
<h3><span class="header-section-number">1.1.1</span> 安装 R 和 RStudio</h3>
<p><em>If your instructor has provided you with a link and access to RStudio Server, then you can skip this section. We do recommend though after a few months of working on the RStudio Server that you return to these instructions. If you don’t know what RStudio Server is, then please read this section.</em></p>
<p>You will first need to download and install both R and RStudio (Desktop version) on your computer.</p>
<ol style="list-style-type: decimal">
<li><a href="https://cran.r-project.org/">Download and install R</a>.
<ul>
<li>Note: You must do this first.</li>
<li>Click on the download link corresponding to your computer’s operating system.</li>
</ul></li>
<li><a href="https://www.rstudio.com/products/rstudio/download3/">Download and install RStudio</a>.
<ul>
<li>Scroll down to “Installers for Supported Platforms”</li>
<li>Click on the download link corresponding to your computer’s operating system.</li>
</ul></li>
</ol>
<p>Optional: If you need more detailed instructions on how to install R and RStudio, watch this <a href="https://campus.datacamp.com/courses/working-with-the-rstudio-ide-part-1/orientation?ex=3">DataCamp video (1m22s)</a>.</p>
</div>
<div id="rstudior" class="section level3">
<h3><span class="header-section-number">1.1.2</span> 在RStudio中使用R</h3>
<p>Recall our car analogy from above. Much as we don’t drive a car by interacting directly with the engine but rather by using elements on the car’s dashboard, we won’t be using R directly but rather we will use RStudio’s interface. After you install R and RStudio on your computer, you’ll have two new programs AKA applications you can open. We will always work in RStudio and not R. In other words:</p>
<table>
<thead>
<tr class="header">
<th align="center">R: Do not open this</th>
<th align="center">RStudio: Open this</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><img src="https://cran.r-project.org/Rlogo.svg" alt="Drawing" style="height: 100px;"/></td>
<td align="center"><img src="https://www.rstudio.com/wp-content/uploads/2014/06/RStudio-Ball.png" alt="Drawing" style="height: 100px;"/></td>
</tr>
</tbody>
</table>
<p>After you open RStudio, you should see the following:</p>
<p><img src="images/rstudio.png" /></p>
<p>Watch the following <a href="https://campus.datacamp.com/courses/working-with-the-rstudio-ide-part-1/orientation?ex=5">DataCamp video (4m10s)</a> to learn about the different <em>panes</em> in RStudio, in particular the <em>Console pane</em> where you will later run R code.</p>
<hr />
</div>
</div>
<div id="code" class="section level2">
<h2><span class="header-section-number">1.2</span> 如果开始编写R语言?</h2>
<p>Now that you’re set up with R and RStudio, you are probably asking yourself “OK. Now how do I use R?” The first thing to note as that unlike other software like Excel, STATA, or SAS that provide <a href="https://en.wikipedia.org/wiki/Point_and_click">point and click</a> interfaces, R is an <a href="https://en.wikipedia.org/wiki/Interpreted_language">interpreted language</a>, meaning you have to enter in R commands written in R code i.e. you have to program in R (we use the terms “coding” and “programming” interchangeably in this book).</p>
<p>While it is not required to be a seasoned coder/computer programmer to use R, there is still a set of basic programming concepts that R users need to understand. Consequently, while this book is not a book on programming, you will still learn just enough of these basic programming concepts needed to explore and analyze data effectively.</p>
<div id="programming-concepts" class="section level3">
<h3><span class="header-section-number">1.2.1</span> 基本编程概念和术语</h3>
<p>To introduce you to many of these basic programming concepts and terminology, we direct you to the following DataCamp online interactive tutorials. For each of the tutorials, we give a list of the basic programming concepts covered. Note that in this book, we will use a different font to distinguish regular font from <code>computer_code</code>.</p>
<p>It is important to note that while these tutorials serve as excellent introductions, a single pass through them is insufficient for long-term learning and retention. The ultimate tools for long-term learning and retention are “learning by doing” and repetition, something we will have you do over the course of the entire book and we encourage this process as much as possible as you learn any new skill.</p>
<ul>
<li>From the <a href="https://www.datacamp.com/courses/free-introduction-to-r">Introduction to R</a> course complete the following chapters. As you work through the chapters, carefully note the important terms and what they are used for. We recommend you do so in a notebook that you can easily refer back to.
<ul>
<li><a href="https://campus.datacamp.com/courses/free-introduction-to-r/chapter-1-intro-to-basics-1?ex=1">Chapter 1 Intro to basics</a>:
<ul>
<li>Console pane: where you enter in commands</li>
<li>Objects: where values are saved, how to assign values to objects.</li>
<li>Data types: integers, doubles/numerics, logicals, characters.<br />
</li>
</ul></li>
<li><a href="https://campus.datacamp.com/courses/free-introduction-to-r/chapter-2-vectors-2?ex=1">Chapter 2 Vectors</a>:
<ul>
<li>Vectors: a series of values.</li>
</ul></li>
<li><a href="https://campus.datacamp.com/courses/free-introduction-to-r/chapter-4-factors-4?ex=1">Chapter 4 Factors</a>:
<ul>
<li><em>Categorical data</em> (as opposed to <em>numerical data</em>) are represented in R as <code>factor</code>s.</li>
</ul></li>
<li><a href="https://campus.datacamp.com/courses/free-introduction-to-r/chapter-5-data-frames?ex=1">Chapter 5 Data frames</a>:
<ul>
<li>Data frames are analogous to rectangular spreadsheets: they are representations of datasets in R where the rows correspond <em>observations</em> and the columns correspond to <em>variables</em> that describe the observations. We will revisit this later in Section <a href="#nycflights13">1.4</a>.</li>
</ul></li>
</ul></li>
<li>From the <a href="https://www.datacamp.com/courses/intermediate-r">Intermediate R</a> course complete the following chapters:
<ul>
<li><a href="https://campus.datacamp.com/courses/intermediate-r/chapter-1-conditionals-and-control-flow?ex=1">Chapter 1 Conditionals and Control Flow</a>:
<ul>
<li>Testing for equality in R using <code>==</code> (and not <code>=</code> which is typically used for assignment). Ex: <code>2 + 1 == 3</code> compares <code>2 + 1</code> to <code>3</code> and is correct R syntax, while <code>2 + 1 = 3</code> is not and is incorrect R syntax.</li>
<li>Boolean algebra: <code>TRUE/FALSE</code> statements and mathematical operators such as <code>&lt;</code> (less than), <code>&lt;=</code> (less than or equal), and <code>!=</code> (not equal to).</li>
<li>Logical operators: <code>&amp;</code> representing “and”, <code>|</code> representing “or”. Ex: <code>(2 + 1 == 3) &amp; (2 + 1 == 4)</code> returns <code>FALSE</code> while <code>(2 + 1 == 3) | (2 + 1 == 4)</code> returns <code>TRUE</code>.</li>
</ul></li>
<li><a href="https://campus.datacamp.com/courses/intermediate-r/chapter-3-functions?ex=1">Chapter 3 Functions</a>:
<ul>
<li>Concept of functions: they take in inputs (called <em>arguments</em>) and return outputs.</li>
<li>You either manually specify a function’s arguments or use the function’s <em>defaults</em>.</li>
</ul></li>
</ul></li>
</ul>
<p>This list is by no means an exhaustive list of all the programming concepts and terminology needed to become a savvy R user; such a list would be so large it wouldn’t be very useful, especially for novices. Rather, we feel this is the bare minimum you need to know before you get started; the rest we feel you can learn as you go. Remember that your knowledge of all of these concepts will build as you get better and better at “speaking R” and getting used to its syntax.</p>
</div>
<div id="section-1.2.2" class="section level3">
<h3><span class="header-section-number">1.2.2</span> 学习编程的提示</h3>
<p>Learning to code/program is very much like learning a foreign language, it can be very daunting and frustrating at first. However just as with learning a foreign language, if you put in the effort and are not afraid to make mistakes, anybody can learn. Lastly, there are a few useful things to keep in mind as you learn to program:</p>
<ul>
<li><strong>Computers are stupid</strong>: You have to tell a computer everything it needs to do. Furthermore, your instructions can’t have any mistakes in them, nor can they be ambiguous in any way.</li>
<li><strong>Take the “copy/paste/tweak” approach</strong>: Especially when learning your first programming language, it is often much easier to taking existing code that you know works and modify it to suit your ends, rather than trying to write new code from scratch. We call this the <em>copy/paste/tweak</em> approach. So early on, we suggest not trying to code from scratch, but please take the code we provide throughout this book and play around with it!</li>
<li><strong>Practice is key</strong>: Just as the only solution to improving your foreign language skills is practice, so also the only way to get better at R is through practice. Don’t worry however, we’ll give you plenty of opportunities to practice!</li>
</ul>
<hr />
</div>
</div>
<div id="packages" class="section level2">
<h2><span class="header-section-number">1.3</span> 什么是 R packages?</h2>
<p>Another point of confusion with new R users is the notion of a package. R packages extend the functionality of R by providing additional functions, data, and documentation and can be downloaded for free from the internet. They are written by a world-wide community of R users. For example, among the many packages we will use in this book are the</p>
<ul>
<li><code>ggplot2</code> package for data visualization in Chapter <a href="#viz"><strong>??</strong></a></li>
<li><code>dplyr</code> package for data wrangling in Chapter <a href="#wrangling"><strong>??</strong></a></li>
</ul>
<p>There are two key things to remember about R packages:</p>
<ol style="list-style-type: decimal">
<li><em>Installation</em>: Most packages are not installed by default when you install R and RStudio. You need to install a package before you can use it. Once you’ve installed it, you likely don’t need to install it again unless you want to update it to a newer version of the package.</li>
<li><em>Loading</em>: Packages are not loaded automatically when you open RStudio. You need to load them every time you open RStudio using the <code>library()</code> command.</li>
</ol>
<p>A good analogy for R packages is they are like apps you can download onto a mobile phone:</p>
<table>
<thead>
<tr class="header">
<th align="center">R: A new phone</th>
<th align="center">R Packages: Apps you can download</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><img src="images/iphone.jpg" alt="Drawing" style="height: 200px;"/></td>
<td align="center"><img src="images/apps.jpg" alt="Drawing" style="height: 200px;"/></td>
</tr>
</tbody>
</table>
<p>So, expanding on this analogy a bit:</p>
<ol style="list-style-type: decimal">
<li>R is like a new mobile phone. It has a certain amount of functionality when you use it for the first time, but it doesn’t have everything.</li>
<li>R packages are like the apps you can download onto your phone, much like those offered in the App Store and Google Play. For example: Instagram.</li>
<li>In order to use a package, just like in order to use Instagram, you must:
<ol style="list-style-type: decimal">
<li>First download it and install it. You do this only once.</li>
<li>Load it, or in other words, “open” it, using the <code>library()</code> command.</li>
</ol></li>
</ol>
<p>So just as you can only start sharing photos with your friends on Instagram if you first install the app and then open it, you can only access an R package’s data and functions if you first install the package and then load it with the <code>library()</code> command. Let’s cover these two steps:</p>
<div id="-package" class="section level3">
<h3><span class="header-section-number">1.3.1</span> 安装 Package</h3>
<p>(Note that if you are working on an RStudio Server, you probably will not need to install your own packages as that has been already done for you. Still it is important that you know this process for later when you are not using the RStudio Server but rather your own installation of RStudio Desktop.)</p>
<p>There are two ways to install an R package. For example, to install the <code>ggplot2</code> package:</p>
<ol style="list-style-type: decimal">
<li><strong>Easy way</strong>: In the Files pane of RStudio:
<ol style="list-style-type: lower-alpha">
<li>Click on the “Packages” tab</li>
<li>Click on “Install”</li>
<li>Type the name of the package under “Packages (separate multiple with space or comma):” In this case, type <code>ggplot2</code></li>
<li>Click “Install”</li>
</ol></li>
<li><strong>Alternative way</strong>: In the Console pane run <code>install.packages(&quot;ggplot2&quot;)</code> (you must include the quotation marks).</li>
</ol>
<p>Repeat this for the <code>dplyr</code> and <code>nycflights13</code> packages.</p>
<p><strong>Note</strong>: You only have to install a package once, unless you want to update an already installed package to the latest version. If you want to update a package to the latest version, then re-install it by repeating the above steps.</p>
</div>
<div id="-package" class="section level3">
<h3><span class="header-section-number">1.3.2</span> 加载 Package</h3>
<p>After you’ve installed a package, you can now load it using the <code>library()</code> command. For example, to load the <code>ggplot2</code> and <code>dplyr</code> packages, run the following code in the Console pane:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(dplyr)</code></pre>
<p><strong>Note</strong>: You have to reload each package you want to use every time you open a new session of RStudio. This is a little annoying to get used to and will be your most common error as you begin. When you see an error such as</p>
<pre><code>Error: could not find function</code></pre>
<p>remember that this likely comes from you trying to use a function in a package that has not been loaded. Remember to run the <code>library()</code> function with the appropriate package to fix this error.</p>
<hr />
</div>
</div>
<div id="nycflights13" class="section level2">
<h2><span class="header-section-number">1.4</span> 探索 你的第一个数据集</h2>
<p>Let’s put everything we’ve learned so far into practice and start exploring some real data! Data comes to us in a variety of formats, from pictures to text to numbers. Throughout this book, we’ll focus on datasets that can be stored in a spreadsheet as that is among the most common way data is collected in the many fields. Remember from Subsection <a href="#programming-concepts">1.2.1</a> that these “spreadsheet”-type datasets are called <em>data frames</em> in R and we will focus on working with data frames throughout this book.</p>
<p>Let’s first load all the packages needed for this chapter (This assumes you’ve already installed them. Read Section <a href="#packages">1.3</a> for information on how to install and load R packages if you haven’t already.) At the beginning of all subsequent chapters in this text, we’ll always have a list of packages similar to what follows that you should have installed and loaded to work with that chapter’s R code.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)

<span class="co"># Be sure to install these first!</span>
<span class="kw">library</span>(nycflights13)</code></pre>
<pre><code>## Warning: package &#39;nycflights13&#39; was built under R version 3.5.2</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(knitr)</code></pre>
<div id="nycflights13-package" class="section level3">
<h3><span class="header-section-number">1.4.1</span> nycflights13 package</h3>
<p>We likely have all flown on airplanes or know someone who has. Air travel has become an ever-present aspect in many people’s lives. If you live in or are visiting a relatively large city and you walk around that city’s airport, you see gates showing flight information from many different airlines. And you will frequently see that some flights are delayed because of a variety of conditions. Are there ways that we can avoid having to deal with these flight delays?</p>
<p>We’d all like to arrive at our destinations on time whenever possible. (Unless you secretly love hanging out at airports. If you are one of these people, pretend for the moment that you are very much anticipating being at your final destination.) Throughout this book, we’re going to analyze data related to flights contained in the <code>nycflights13</code> package <span class="citation">[@R-nycflights13]</span>. Specifically, this package contains five datasets saved as “data frames” (see Section <a href="#code">1.2</a>) with information about all domestic flights departing from New York City in 2013, from either Newark Liberty International (EWR), John F. Kennedy International (JFK), or LaGuardia (LGA) airports:</p>
<ul>
<li><code>flights</code>: information on all 336,776 flights</li>
<li><code>airlines</code>: translation between two letter IATA carrier codes and names (16 in total)</li>
<li><code>planes</code>: construction information about each of 3,322 planes used</li>
<li><code>weather</code>: hourly meteorological data (about 8705 observations) for each of the three NYC airports</li>
<li><code>airports</code>: airport names and locations</li>
</ul>
</div>
<div id="flights-" class="section level3">
<h3><span class="header-section-number">1.4.2</span> flights 数据集</h3>
<p>We will begin by exploring the <code>flights</code> data frame that is included in the <code>nycflights13</code> package and getting an idea of its structure. Run the following in your code in your console: it loads in the <code>flights</code> dataset into your Console. Note depending on the size of your monitor, the output may vary slightly.</p>
<pre class="sourceCode r"><code class="sourceCode r">flights</code></pre>
<pre><code>## # A tibble: 336,776 x 19
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
##  1  2013     1     1      517            515         2      830
##  2  2013     1     1      533            529         4      850
##  3  2013     1     1      542            540         2      923
##  4  2013     1     1      544            545        -1     1004
##  5  2013     1     1      554            600        -6      812
##  6  2013     1     1      554            558        -4      740
##  7  2013     1     1      555            600        -5      913
##  8  2013     1     1      557            600        -3      709
##  9  2013     1     1      557            600        -3      838
## 10  2013     1     1      558            600        -2      753
## # ... with 336,766 more rows, and 12 more variables: sched_arr_time &lt;int&gt;,
## #   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,
## #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,
## #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<p>Let’s unpack this output:</p>
<ul>
<li><code>A tibble: 336,776 x 19</code>: a <code>tibble</code> is a <a href="https://blog.rstudio.org/2016/03/24/tibble-1-0-0/#tibbles-vs-data-frames">kind of data frame</a>. This particular data frame has
<ul>
<li><code>336,776</code> rows</li>
<li><code>19</code> columns corresponding to 19 variables describing each observation</li>
</ul></li>
<li><code>year month day dep_time sched_dep_time dep_delay arr_time</code> are different columns, in other words variables, of this data frame.</li>
<li>We then have the first 10 rows of observations corresponding to 10 flights.</li>
<li><code>... with 336,766 more rows, and 11 more variables:</code> indicating to us that 336,766 more rows of data and 11 more variables could not fit in this screen.</li>
</ul>
<p>Unfortunately, this output does not allow us to explore the data very well. Let’s look at different tools to explore data frames.</p>
</div>
<div id="exploredataframes" class="section level3">
<h3><span class="header-section-number">1.4.3</span> 探索数据集</h3>
<p>Among the many ways of getting a feel for the data contained in a data frame such as <code>flights</code>, we present three functions that take as their argument the data frame in question:</p>
<ol style="list-style-type: decimal">
<li>Using the <code>View()</code> function built for use in RStudio. We will use this the most.</li>
<li>Using the <code>glimpse()</code> function loaded via <code>dplyr</code> package</li>
<li>Using the <code>kable()</code> function in the <code>knitr</code> package</li>
<li>Using the <code>$</code> operator to view a single variable in a data frame</li>
</ol>
<p><strong>1. <code>View()</code></strong>:</p>
<p>Run <code>View(flights)</code> in your Console in RStudio and explore this data frame in the resulting pop-up viewer. You should get into the habit of always <code>View</code>ing any data frames that come your way.</p>
<p>Note the capital “V” in <code>View</code>. R is case-sensitive so you’ll receive an error is you run <code>view(flights)</code> instead of <code>View(flights)</code>.</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC2.1)</strong> What does any <em>ONE</em> row in this <code>flights</code> dataset refer to?</p>
<ul>
<li>A. Data on an airline</li>
<li>B. Data on a flight</li>
<li>C. Data on an airport</li>
<li>D. Data on multiple flights</li>
</ul>
<div class="learncheck">

</div>
<p>By running <code>View(flights)</code>, we see the different <em>variables</em> listed in the columns and we see that there are different types of variables. Some of the variables like <code>distance</code>, <code>day</code>, and <code>arr_delay</code> are what we will call <em>quantitative</em> variables. These variables are numerical in nature. Other variables here are <em>categorical</em>.</p>
<p>Note that if you look in the leftmost column of the <code>View(flights)</code> output, you will see a column of numbers. These are the row numbers of the dataset. If you glance across a row with the same number, say row 5, you can get an idea of what each row corresponds to. In other words, this will allow you to identify what object is being referred to in a given row. This is often called the <em>observational unit</em>. The <em>observational unit</em> in this example is an individual flight departing New York City in 2013. You can identify the observational unit by determining what the <em>thing</em> is that is being measured in each of the variables.</p>
<p><strong>2. <code>glimpse()</code></strong>:</p>
<p>The second way to explore a data frame is using the <code>glimpse()</code> function that you can access after you’ve loaded the <code>dplyr</code> package. It provides us with much of the above information and more.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">glimpse</span>(flights)</code></pre>
<pre><code>## Observations: 336,776
## Variables: 19
## $ year           &lt;int&gt; 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013,...
## $ month          &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
## $ day            &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
## $ dep_time       &lt;int&gt; 517, 533, 542, 544, 554, 554, 555, 557, 557, 55...
## $ sched_dep_time &lt;int&gt; 515, 529, 540, 545, 600, 558, 600, 600, 600, 60...
## $ dep_delay      &lt;dbl&gt; 2, 4, 2, -1, -6, -4, -5, -3, -3, -2, -2, -2, -2...
## $ arr_time       &lt;int&gt; 830, 850, 923, 1004, 812, 740, 913, 709, 838, 7...
## $ sched_arr_time &lt;int&gt; 819, 830, 850, 1022, 837, 728, 854, 723, 846, 7...
## $ arr_delay      &lt;dbl&gt; 11, 20, 33, -18, -25, 12, 19, -14, -8, 8, -2, -...
## $ carrier        &lt;chr&gt; &quot;UA&quot;, &quot;UA&quot;, &quot;AA&quot;, &quot;B6&quot;, &quot;DL&quot;, &quot;UA&quot;, &quot;B6&quot;, &quot;EV&quot;,...
## $ flight         &lt;int&gt; 1545, 1714, 1141, 725, 461, 1696, 507, 5708, 79...
## $ tailnum        &lt;chr&gt; &quot;N14228&quot;, &quot;N24211&quot;, &quot;N619AA&quot;, &quot;N804JB&quot;, &quot;N668DN...
## $ origin         &lt;chr&gt; &quot;EWR&quot;, &quot;LGA&quot;, &quot;JFK&quot;, &quot;JFK&quot;, &quot;LGA&quot;, &quot;EWR&quot;, &quot;EWR&quot;...
## $ dest           &lt;chr&gt; &quot;IAH&quot;, &quot;IAH&quot;, &quot;MIA&quot;, &quot;BQN&quot;, &quot;ATL&quot;, &quot;ORD&quot;, &quot;FLL&quot;...
## $ air_time       &lt;dbl&gt; 227, 227, 160, 183, 116, 150, 158, 53, 140, 138...
## $ distance       &lt;dbl&gt; 1400, 1416, 1089, 1576, 762, 719, 1065, 229, 94...
## $ hour           &lt;dbl&gt; 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5,...
## $ minute         &lt;dbl&gt; 15, 29, 40, 45, 0, 58, 0, 0, 0, 0, 0, 0, 0, 0, ...
## $ time_hour      &lt;dttm&gt; 2013-01-01 05:00:00, 2013-01-01 05:00:00, 2013...</code></pre>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC2.2)</strong> What are some examples in this dataset of <strong>categorical</strong> variables? What makes them different than <strong>quantitative</strong> variables?</p>
<p><strong>(LC2.3)</strong> What does <code>int</code>, <code>dbl</code>, and <code>chr</code> mean in the output above?</p>
<div class="learncheck">

</div>
<p>We see that <code>glimpse</code> will give you the first few entries of each variable in a row after the variable. In addition, the <em>data type</em> (See Subsection <a href="#programming-concepts">1.2.1</a>) of the variable is given immediately after each variable’s name inside <code>&lt; &gt;</code>. Here, <code>int</code> and <code>num</code> refer to quantitative variables. In contrast, <code>chr</code> refers to categorical variables. One more type of variable is given here with the <code>time_hour</code> variable: <code>dttm</code>. As you may suspect, this variable corresponds to a specific date and time of day.</p>
<p><strong>3. <code>kable()</code></strong>:</p>
<p>The final way to explore the entirety of a data frame is using the <code>kable()</code> function from the <code>knitr</code> package. Let’s explore the different carrier codes for all the airlines in our dataset two ways. Run both of these in your Console:</p>
<pre class="sourceCode r"><code class="sourceCode r">airlines
<span class="kw">kable</span>(airlines)</code></pre>
<p>At first glance of both outputs, it may not appear that there is much difference. However, we’ll see later on, especially when using a tool for document production called <a href="http://rmarkdown.rstudio.com/lesson-1.html">R Markdown</a>, that the latter produces output that is much more legible.</p>
<p><strong>4. <code>$</code> operator</strong></p>
<p>Lastly, the <code>$</code> operator allows us to explore a single variable within a data frame. For example, run the following in your console</p>
<pre class="sourceCode r"><code class="sourceCode r">airlines
airlines<span class="op">$</span>name</code></pre>
<p>We used the <code>$</code> operator to extract only the <code>name</code> variable and return it as a vector of length 16. We will only be occasionally exploring data frames using this operator.</p>
</div>
<div id="section-1.4.4" class="section level3">
<h3><span class="header-section-number">1.4.4</span> 帮助文件</h3>
<p>Another nice feature of R is the help system. You can get help in R by entering a <code>?</code> before the name of a function or data frame in question and you will be presented with a page showing the documentation. For example, let’s look at the help file for the <code>flights</code> data frame:</p>
<pre class="sourceCode r"><code class="sourceCode r">?flights</code></pre>
<p>A help file should pop-up in the Help pane of RStudio. Note the content of this particular help file is also accessible on the <a href="https://cran.r-project.org/web/packages/nycflights13/nycflights13.pdf">web</a> on page 3 of the PDF document. You should get in the habit of consulting the help file of any function or data frame in R about which you have questions.</p>
<hr />
</div>
</div>
<div id="section-1.5" class="section level2">
<h2><span class="header-section-number">1.5</span> 结论</h2>
<p>We’ve given you what we feel are the most essential concepts to know before you can start exploring data in R. Is this chapter exhaustive? Absolutely not. To try to include everything in this chapter would make the chapter so large it wouldn’t be useful! However, as we stated earlier, the best way to learn R is to learn by doing. Now let’s get into learning about how to create good stories about and with data. In Chapter <a href="#viz"><strong>??</strong></a>, we start with what we feel is the most important tool in a data scientist’s toolbox: data visualization.</p>
<div id="section-1.5.1" class="section level3">
<h3><span class="header-section-number">1.5.1</span> 下一集有什么内容?</h3>
<p>We’ll now start the “data science” portion of the in Chapter <a href="#viz"><strong>??</strong></a>, where we will further explore the datasets include the <code>nycflights13</code> package. We’ll see that data visualization is a powerful tool to add to our toolbox for exploring what is going on in a dataset beyond the <code>View</code> and <code>glimpse</code> functions we introduced in this chapter.</p>
<center>
<img src="images/flowcharts/flowchart/flowchart.004.png" title="ModernDive flowchart" width="800"/>
</center>
<!--
### Data Packages

Some of the datasets we will analyze in this class are accessible via R packages. For example:

- flights leaving New York City in 2013 in the `nycflights13` package
- profiles of OKCupid users in San Francisco in the `okcupiddata` package
- IMDB movie ratings in the `ggplot2movies` package

By focusing on a few large data sources, it is our hope that you'll be able to see how each of the chapters is interconnected.  You'll see how the data being "tidy" (See Chapter \@ref(tidy)) leads into data visualization and wrangling in exploratory data analysis and how those concepts tie into inference and regression.

We will keep a running list of R packages you will need to have installed to complete the analysis as well here in the `needed_pkgs` character vector.  You can check if you have all of the needed packages installed by running all of the lines below in the next chunk of R code.  The last lines including the `if` will install them as needed (i.e., download their needed files from the internet to your hard drive and install them for your use).

You can run the `library` function on them to load them into your current analysis.  Prior to each analysis where a package is needed, you will see the corresponding `library` function in the text.  Make sure to check the top of the chapter to see if a package was loaded there.
-->
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/moderndive/moderndive_book/edit/master/%s",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"search": false
});
});
</script>

</body>

</html>
